### ISSUE TITLE
mac osx install broken

### ISSUE THREAD

**Issue by glasmasin** [kovetskiy/spinner-go#2]
On mac:
> go get github.com/kovetskiy/spinner-go                                         
# github.com/kovetskiy/spinner-go
code/go/src/github.com/kovetskiy/spinner-go/spinner.go:146:12: undefined: getTerminalWidth

I'm guess the recent change may have broken it.

**Comment by kovetskiy** [comment]
@glasmasin please check now, it should be fixed
